// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return [
      '$scope', '$rootScope', '$stateParams', function($scope, $rootScope, $stateParams) {
        console.log('mainpage controller with state parameters', $stateParams);
        return $scope.$apply();
      }
    ];
  });

}).call(this);
