// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return [
      '$scope', '$rootScope', '$stateParams', function($scope, $rootScope, $stateParams) {
        console.log('navigation controller with state parameters', $stateParams);
        if (typeof self.isLoggedIn === 'undefined') {
          self.isLoggedIn = true;
        }
        self.isLoggedIn = true;
        $scope.navigation = [
          {
            url: '#/',
            label: 'Etusivu',
            show: true
          }, {
            url: '#/login',
            label: 'Kirjaudu sisään',
            show: !self.isLoggedIn
          }, {
            url: '#/create',
            label: 'Luo tuote',
            show: self.isLoggedIn
          }, {
            url: '#/logout',
            label: 'Kirjaudu ulos',
            show: self.isLoggedIn
          }
        ];
        $scope.isActive = function() {
          if (window.location.hash === this.item.url) {
            return true;
          } else {
            return false;
          }
        };
        return $scope.$apply();
      }
    ];
  });

}).call(this);
