// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var directive;
    return directive = function($http, $timeout) {
      var dir;
      return dir = {
        templateUrl: 'app/partials/directives/template.html',
        restrict: 'EA',
        require: '^ngModel',
        scope: {
          ngModel: '='
        },
        link: function($scope, el, attrs) {
          return console.log('template directive triggered');
        }
      };
    };
  });

}).call(this);
