// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'uiRouter', 'filters', 'services', 'directives', 'controllers', 'angularResource'], function(angular) {
    'use strict';
    var module;
    module = angular.module('products', ['ngResource', 'products.controllers', 'products.filters', 'products.services', 'products.directives', 'ui.router']);
    return module;
  });

}).call(this);
