// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'uiRouter', 'filters', 'services', 'directives', 'controllers', 'angularResource'], function(angular) {
    'use strict';
    var module;
    module = angular.module('newApp', ['ngResource', 'newApp.controllers', 'newApp.filters', 'newApp.services', 'newApp.directives', 'ui.router']);
    return module;
  });

}).call(this);
