// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'services'], function(angular) {
    'use strict';
    var module;
    module = angular.module('newApp.controllers', ['newApp.services']);
    module.controller('Mainpage', [
      '$scope', '$injector', function($scope, $injector) {
        return require(['controllers/mainpage'], function(mainpage) {
          return $injector.invoke(mainpage, this, {
            '$scope': $scope
          });
        });
      }
    ]);
    module.controller('Create', [
      '$scope', '$injector', function($scope, $injector) {
        return require(['controllers/create'], function(create) {
          return $injector.invoke(create, this, {
            '$scope': $scope
          });
        });
      }
    ]);
    module.controller('Navigation', [
      '$scope', '$injector', function($scope, $injector) {
        return require(['controllers/navigation'], function(navigation) {
          return $injector.invoke(navigation, this, {
            '$scope': $scope
          });
        });
      }
    ]);
    return module;
  });

}).call(this);
