// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'services', 'directives/template'], function(angular, services, template) {
    'use strict';
    var module;
    module = angular.module('newApp.directives', ['newApp.services']);
    module.directive('apiTemplate', template);
    return module;
  });

}).call(this);
