// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'services'], function(angular, services) {
    'use strict';
    var module;
    module = angular.module('newApp.filters', ['newApp.services']);
    return module.filter('interpolate', [
      'version', function(version) {
        return function(text) {
          return String(text).replace(/\%VERSION\%/mg, version);
        };
      }
    ]);
  });

}).call(this);
