// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'app'], function(angular, app) {
    'use strict';
    return app.config(function($stateProvider, $urlRouterProvider) {
      var navigationView;
      navigationView = {
        controller: 'Navigation',
        templateUrl: 'app/partials/navigation.html'
      };
      $stateProvider.state('mainpage', {
        url: '/',
        views: {
          content: {
            controller: 'Mainpage',
            templateUrl: 'app/partials/mainpage.html'
          },
          navigation: navigationView
        }
      });
      $stateProvider.state('create', {
        url: '/create',
        views: {
          content: {
            templateUrl: 'app/partials/create.html',
            controller: 'Create'
          },
          navigation: navigationView
        }
      });
      return $urlRouterProvider.otherwise('/');
    });
  });

}).call(this);
