// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular'], function(angular) {
    'use strict';
    var module;
    module = angular.module('newApp.services', []);
    return module.value('version', '0.1');
  });

}).call(this);
